version: "3"

services: 
  web:
    container_name: myapisrv
    restart: always
    build: .
    ports: 
      - "3000:3000"
    links: 
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: myapimongo36
    image: mongo:3.6.21
    ports: 
      - "27036:27017"
    restart: always
    logging:
      driver: none
    volumes:
      - /data/dockers/mymongo36/volumes/data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8036:8081
